#ifndef UNITAS_ABI_SYSCALL_H
#define UNITAS_ABI_SYSCALL_H

#define UNITAS_SYS_EXIT 0
#define UNITAS_SYS_WRITE 1
#define UNITAS_SYS_READ 2
#define UNITAS_SYS_OPEN 3
#define UNITAS_SYS_CLOSE 4
#define UNITAS_SYS_LSEEK 5
#define UNITAS_SYS_BRK 6
#define UNITAS_SYS_GETDENTS64 7
#define UNITAS_SYS_UNAME 8
#define UNITAS_SYS_UNLINK 9
#define UNITAS_SYSCALL_VECTOR 0x81

#define UNITAS_O_WRONLY 1
#define UNITAS_O_RDWR 2
#define UNITAS_O_CREAT 0x40
#define UNITAS_O_TRUNC 0x200

#define UNITAS_SEEK_SET 0
#define UNITAS_SEEK_CUR 1
#define UNITAS_SEEK_END 2

#endif
